artifact_location: /home/nour/Smart Parking YOLO/runs/mlflow/0
creation_time: 1778342612630
experiment_id: '0'
last_update_time: 1778342612630
lifecycle_stage: active
name: Default
workspace: default
