artifact_location: /home/nour/Smart Parking YOLO/runs/mlflow/504869130670556626
creation_time: 1778342612637
experiment_id: '504869130670556626'
last_update_time: 1778342612637
lifecycle_stage: active
name: /home/nour/Smart Parking YOLO/runs
workspace: default
